name: h2o-mojo-env-v2
channels:
  - conda-forge
dependencies:
  - python=3.9
  - openjdk=11.0.15
  - pip
  - requests
  - pyyaml
  - pandas
  - typing_extensions
  - pip:
    - azureml-core
    - azureml-inference-server-http
    - h2o==3.40.0.1
    - azure-ai-ml==1.27.1
    - azure-core==1.34.0
    - azure-identity==1.23.0
    - azure-storage-blob==12.25.1
    - fsspec
