name: Deploy Azure ML Pipeline (Dev to Prod)

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  deploy-to-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List files
        run: |
          echo "Listing files in current directory: $(pwd)"
          ls -F
          echo "Listing files recursively in current directory:"
          ls -RF .
          echo "Checking for 'components' directory:"
          if [ -d "components" ]; then
            echo "'components' directory found."
            ls -RF components/
          else
            echo "'components' directory NOT found!"
          fi

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-ml azure-identity

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Pipeline in Dev
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_WORKSPACE: ${{ secrets.AZURE_WORKSPACE }}
        run: python run_pipeline.py
