name: Deploy Azure ML Pipeline (Dev to Prod)

on:
  push:
    branches:
      - dev
      - main # Added main branch for direct pushes to maina
  pull_request:
    branches:
      - main
    types: [closed] # Triggers on PR merge into main
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy-to-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: development # Ensure this GitHub environment exists and is configured with required secrets
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required to checkout code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List files
        run: |
          echo "Listing files in current directory: $(pwd)"
          ls -F
          echo "Listing files recursively in current directory:"
          ls -RF .
          echo "Checking for 'components' directory:"
          if [ -d "components" ]; then
            echo "'components' directory found."
            ls -RF components/
          else
            echo "'components' directory NOT found!"
          fi

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-ml azure-identity

      - name: Log in to Azure with OIDC
        uses: azure/login@v1.4.6 # Use a specific version for stability, check marketplace for latest
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # No 'creds' needed with OIDC when client-id, tenant-id, subscription-id are provided directly.
          # The azure/login action will use these for OIDC.

      - name: Run Pipeline in Dev
        env:
          SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE }}
        run: python run_pipeline.py

  deploy-to-prod:
    # Trigger on push to main or on closed PR targeting main
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: production # Require manual approval in GitHub settings
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required to checkout code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List files
        run: |
          echo "Listing files in current directory: $(pwd)"
          ls -F
          echo "Listing files recursively in current directory:"
          ls -RF .
          echo "Checking for 'components' directory:"
          if [ -d "components" ]; then
            echo "'components' directory found."
            ls -RF components/
          else
            echo "'components' directory NOT found!"
          fi

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-ml azure-identity

      - name: Log in to Azure with OIDC
        uses: azure/login@v1.4.6 # Use a specific version for stability
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Pipeline in Prod
        env:
          SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE }}
        run: python run_pipeline.py
